@startuml
'https://plantuml.com/class-diagram

interface Thing {
    + weight: Double
}

abstract class Asset {
    + name: String
    + price: Int
}

abstract class TangibleAsset extends Asset implements Thing {
    + color: String
}

abstract class IntangibleAsset extends Asset

class Book extends TangibleAsset {
    + isbn: String
}

class Computer extends TangibleAsset {
    + makerName: String
}

class Patent extends IntangibleAsset



@enduml