@startuml
'https://plantuml.com/class-diagram

interface Thing

abstract class Asset {
    name: String
}

abstract class TangibleAsset extends Asset implements Thing {
    price: Int
    color: String
}

abstract class IntangibleAsset extends Asset

class Book extends TangibleAsset

class Computer extends TangibleAsset

class Patent extends IntangibleAsset



@enduml