@startuml
scale 1

interface Attackable {
    + {abstract} fun attack(slime: Slime)

}

interface Moveable {
    + {abstract} fun move()

}

abstract class Character {
    + name: String
    + hp: Int

    + {abstract} fun attack(slime: Slime)
    - fun run()
}
class Hero extends Character implements Attackable, Moveable{
    + fun attack(slime: Slime)

}

class SuperHero extends Hero {
    + isFlying: Boolean
}
@enduml