@startuml
skinparam classAttributeIconSize 0

interface Thing {
    + {abstract} weight: Double
}

abstract class Asset {
    + name: String
}

abstract class TangibleAsset extends Asset implements Thing {
    + name: String,
    + price: Int,
    + color: String,
    + weight: Double,
}

class Book extends TangibleAsset {
    + name: String,
    + price: Int,
    + color: String,
    + isbn: String,
    + weight: Double,
}

class Computer extends TangibleAsset {
    + name: String,
    + price: Int,
    + color: String,
    + makerName: String,
    + weight: Double,
}

abstract class IntangibleAsset extends Asset {
    + name: String,
}

class Patent extends IntangibleAsset {
    + name: String,
}

@enduml
