@startuml
title 자산 관리 프로그램 클래스 다이어그램

interface Thing {
    + weight: Double
}

abstract class Asset {
    - name: String
    - price: Int
    - color: String
}

abstract class TangibleAsset extends Asset implements Thing {
    - name: String
    - price: Int
    - color: String
    - weight: Double
}

abstract class IntangibleAsset extends Asset {
    - name: String
    - price: Int
    - color: String
}

class Book extends TangibleAsset {
    - isbn: String
}

class Computer extends TangibleAsset {
    - makerName: String
}

class Patent extends IntangibleAsset {
    - patentNumber: String
}

@enduml
