### GET 요청
GET https://jsonplaceholder.typicode.com/posts/1

### POST 요청
POST https://jsonplaceholder.typicode.com/posts/
Content-Type: application/json

{
  "userId": 5,
  "title": "hello",
  "body": "World"
}

### PUT 요청
PUT https://jsonplaceholder.typicode.com/posts/100
Content-Type: application/json

{
  "userId": 5,
  "title": "hello",
  "body": "World"
}


### PATCH 요청
PATCH https://jsonplaceholder.typicode.com/posts/100
Content-Type: application/json

{
  "title": "hello"
}


### DELETE 요청
DELETE https://jsonplaceholder.typicode.com/posts/100


### 지하철
GET http://swopenapi.seoul.go.kr/api/subway/sample/json/realtimeStationArrival/0/5/%EC%84%9C%EC%9A%B8%EC%9A%B8